[build]
  # Carpeta donde se generan los archivos estáticos tras hacer npm run build
    publish = "build"
      # Comando para construir tu proyecto
        command = "npm run build"

        [[redirects]]
          # Redirige todas las rutas hacia index.html (necesario en React Router)
            from = "/*"
              to = "/index.html"
                status = 200