[build]
  command = "npm ci && CI= npm run build"   # evita que warnings paren el build
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
